version: "3.7"

services:
  fotos:
    build:
      context: https://github.com/noizwaves/fotos.git
    container_name: fotos
    hostname: fotos
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      ## Change `/path/to/thumbnails_v2` to the directory you want to store generated thumbnails in
      - /path/to/thumbnails_v2:/thumbnails_v2

      ## Change `/path/to/photos` to the directory that contains your photos
      - /path/to/photos:/photos:ro
    restart: unless-stopped
