version: "3.7"

services:
  fotos:
    build:
      context: https://github.com/noizwaves/fotos.git
    container_name: fotos
    hostname: fotos
    user: "1000:1000"
    ports: []
    networks:
      - web
    environment:
      - TZ=America/Denver
      - PORT=3000
    volumes:
      - ~/workspace/fotos/thumbnails_v2:/thumbnails_v2:rw
      - ~/Pictures/iCloud_Photos:/photos:ro
    restart: unless-stopped

  nginx:
    image: nginx:1.19.1
    container_name: fotos_nginx
    hostname: fotos_nginx
    ports:
      - "3000:80"
    networks:
      - web
    environment:
      - TZ=America/Denver
    volumes:
      - ~/workspace/fotos/thumbnails_v2:/usr/share/nginx/html/thumbnails_v2:ro
      - ~/Pictures/iCloud_Photos:/usr/share/nginx/html/photos:ro
      - ./fotos.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

networks:
  web:
    external: true
