version: 2.1

orbs:
   node: circleci/node@4.1


jobs:
  build:
    docker:
      - image: cimg/node:10.24
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          app-dir: frontend
      - node/install-packages:
          pkg-manager: yarn
          app-dir: backend
      - run:
          name: Build frontend
          working_directory: frontend
          command: yarn build

workflows:
  sample: 
    jobs:
      - build
