name: CI

on:
  - push
  - pull_request

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.13.0"
      - name: Build frontend
        run: cd frontend && yarn install && yarn build
      - name: Build backend
        run: cd backend && yarn install
  build-image:
    runs-on: ubuntu-latest
    needs: [build-app]
    steps:
      - name: Log into GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push latest
        uses: docker/build-push-action@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          push: true
          tags: ghcr.io/noizwaves/fotos:latest
      - name: Build and Push ${{ github.sha }}
        uses: docker/build-push-action@v2
        if: ${{ github.ref != 'refs/heads/main' }}
        with:
          push: true
          tags: ghcr.io/noizwaves/fotos:${{ github.sha }}
